apiVersion: apps/v1
kind: Deployment
metadata:
  name: devfile-registry
  labels:
    app: devfile-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devfile-registry
  template:
    metadata:
      labels:
        app: devfile-registry
    spec:
      volumes:
        - name: registry-storage
          persistentVolumeClaim:
            claimName: registry-storage-claim
      containers:
      - name: devfile-registry-metadata
        image: docker.io/johncollier/oci-devfile-registry-metadata:latest
        ports:
        - containerPort: 8080
      - name: devfile-registry
        image: registry:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: devfile-registry
  labels:
    app: devfile-registry
spec:
  ports:
    - port: 8080
      name: devfile-registry-metadata
    - port: 5000
      name: devfile-registry
  selector:
    app: devfile-registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
